remote_theme: giellalt/jekyll-theme-giellalt@main
title: Dictionary for Komi-Zyrian ⇒ Udmurt
description: An electronic dictionary from Komi-Zyrian to Udmurt
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: default
