theme: jekyll-theme-giellalt
title: Dictionary for Komi-Zyrian ⇒ Udmurt
description: An electronic dictionary from Komi-Zyrian to Udmurt

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
